name: Test Send Existing JSON

on:
  workflow_dispatch:

jobs:
  send-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Send to Google Sheets
        run: node WriteToSheet.js
